/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Ellipse2Image from 'src/assets/images/Component7_Ellipse_2.png';
import Line4Image from 'src/assets/images/Component7_Line_4.png';
import CarretRightImage from 'src/assets/images/Component7_Carret_Right.png';
import CursorTypingGifImage from 'src/assets/images/Component7_Cursor_Typing__GIF_.png';
import CursorTypingGif1Image from 'src/assets/images/Component7_Cursor_Typing__GIF__1.png';
import BoutonSignIn1Image from 'src/assets/images/Component7_Bouton_Sign_In.png';
import CircleErrorImage from 'src/assets/images/Component7_circle_error.png';
import { styled } from '@mui/material/styles';
// import ArrowUpRight from 'src/components/ArrowUpRight/ArrowUpRight';
// import ArrowDownRight from 'src/components/ArrowDownRight/ArrowDownRight';
import KeyboardsNumericIPhone from 'src/components/KeyboardsNumericIPhone/KeyboardsNumericIPhone';

const Component71 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `926px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

// const ArrowUpRight1 = styled(ArrowUpRight)(({ theme }) => ({
//   width: `46px`,
//   height: `41px`,
//   position: `absolute`,
//   left: `63px`,
//   top: `416px`,
// }));

// const ArrowDownRight1 = styled(ArrowDownRight)(({ theme }) => ({
//   width: `46px`,
//   height: `41px`,
//   position: `absolute`,
//   left: `63px`,
//   top: `361px`,
// }));

const PaymentAdd = styled('div')({
  backgroundColor: `rgba(28, 23, 23, 1)`,
  borderRadius: `20px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `474px`,
  height: `926px`,
  left: `0px`,
  top: `0px`,
  overflow: `hidden`,
});

const Background = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `226px`,
  height: `226px`,
  left: `-402px`,
  top: `908px`,
});

const Ellipse2 = styled('img')({
  height: `226px`,
  width: `226px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const SignIn = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `700`,
  fontSize: `32px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `77px`,
  textTransform: `none`,
  width: `290px`,
  height: `67px`,
  position: `absolute`,
  left: `75px`,
  top: `28px`,
});

const Group237458 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `301px`,
  height: `260px`,
  left: `81px`,
  top: `95px`,
});

const Group237456 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `301px`,
  height: `260px`,
  left: `0px`,
  top: `0px`,
});

const Forms = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `301px`,
  height: `260px`,
  left: `0px`,
  top: `0px`,
});

const ForgetPasswordText = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `297px`,
  height: `230px`,
  left: `4px`,
  top: `30px`,
});

const Q0278 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `25px`,
  letterSpacing: `2.5px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  width: `141px`,
  height: `52px`,
  position: `absolute`,
  left: `73px`,
  top: `178px`,
});

const Q0Xa233782 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `25px`,
  letterSpacing: `2.5px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  width: `211px`,
  height: `52px`,
  position: `absolute`,
  left: `70px`,
  top: `106px`,
});

const CryptoBalance226Eth = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `1.5px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  width: `135px`,
  height: `67px`,
  position: `absolute`,
  left: `162px`,
  top: `0px`,
});

const Eth = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `2px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  width: `55px`,
  position: `absolute`,
  left: `0px`,
  top: `193px`,
});

const Line = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `120px`,
  height: `0px`,
  left: `0px`,
  top: `0px`,
});

const Line1 = styled('div')({
  border: `1px solid rgba(223, 223, 223, 1)`,
  width: `120px`,
  height: `0px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const WalletBalance956 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `1.5px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  width: `138px`,
  height: `52px`,
  position: `absolute`,
  left: `52px`,
  top: `120px`,
});

const To = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `2px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  width: `55px`,
  position: `absolute`,
  left: `81px`,
  top: `245px`,
});

const Line4 = styled('img')({
  height: `0px`,
  width: `340px`,
  position: `absolute`,
  left: `784px`,
  top: `516px`,
});

const CarretRight = styled('img')({
  height: `48px`,
  width: `45px`,
  position: `absolute`,
  left: `109px`,
  top: `144px`,
});

const BoutonSignIn = styled('div')({
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `116px`,
  height: `45px`,
  left: `64px`,
  top: `379px`,
});

const TxnFees = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `700`,
  fontSize: `15px`,
  letterSpacing: `0.75px`,
  textDecoration: `none`,
  lineHeight: `40px`,
  textTransform: `none`,
  width: `116px`,
  height: `45px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Q109 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `700`,
  fontSize: `15px`,
  letterSpacing: `0.75px`,
  textDecoration: `none`,
  lineHeight: `40px`,
  textTransform: `none`,
  width: `189px`,
  height: `45px`,
  position: `absolute`,
  left: `114px`,
  top: `379px`,
});

const KeyboardsNumericIPho = styled(KeyboardsNumericIPhone)(({ theme }) => ({
  width: `474px`,
  height: `252px`,
  position: `absolute`,
  left: `0px`,
  top: `598px`,
}));

const CursorTypingGif = styled('img')({
  height: `29px`,
  width: `24px`,
  position: `absolute`,
  left: `237px`,
  top: `316px`,
});

const CursorTypingGif1 = styled('img')({
  height: `29px`,
  width: `24px`,
  position: `absolute`,
  left: `338px`,
  top: `241px`,
});

const BoutonSignIn1 = styled('img')({
  height: `60px`,
  width: `400px`,
  position: `absolute`,
  left: `33px`,
  top: `467px`,
});

const CircleError = styled('img')({
  height: `48px`,
  width: `49px`,
  position: `absolute`,
  left: `399px`,
  top: `38px`,
});

function Component7(props) {
  return (
    <Component71 className={props.className}>
      {/* <ArrowUpRight1 />
      <ArrowDownRight1 /> */}
      <PaymentAdd>
        <Background>
          {/* <Ellipse2 src={Ellipse2Image} loading="lazy" alt={'Ellipse 2'} /> */}
        </Background>
        <SignIn>{`Payment`}</SignIn>
        <Group237458>
          <Group237456>
            <Forms>
              <ForgetPasswordText>
                <Q0278>{`0.278`}</Q0278>
                <Q0Xa233782>{`0xa23..3782`}</Q0Xa233782>
                <CryptoBalance226Eth>
                  {`Crypto Balance
    22.6 ETH
`}
                </CryptoBalance226Eth>
                <Eth>{`ETH`}</Eth>
              </ForgetPasswordText>
              <Line>
                <Line1></Line1>
              </Line>
            </Forms>
          </Group237456>
        </Group237458>
        <WalletBalance956>
          {`Wallet Balance
       $95.6 `}
        </WalletBalance956>
        <To>{`To`}</To>
        <Line4 src={Line4Image} loading="lazy" alt={'Line 4'} />
        <CarretRight
          src={CarretRightImage}
          loading="lazy"
          alt={'Carret_Right'}
        />
        <BoutonSignIn>
          <TxnFees>{`Txn fees`}</TxnFees>
        </BoutonSignIn>
        <Q109>{` $1.09 `}</Q109>
        <KeyboardsNumericIPho />
        <CursorTypingGif
          src={CursorTypingGifImage}
          loading="lazy"
          alt={'Cursor/Typing (GIF)'}
        />
        <CursorTypingGif1
          src={CursorTypingGif1Image}
          loading="lazy"
          alt={'Cursor/Typing (GIF)'}
        />
        <BoutonSignIn1
          src={BoutonSignIn1Image}
          loading="lazy"
          alt={'Bouton Sign In'}
        />
        <CircleError
          src={CircleErrorImage}
          loading="lazy"
          alt={'circle-error'}
        />
      </PaymentAdd>
    </Component71>
  );
}

export default Component7;
