/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Ellipse1Image from 'src/assets/images/MainPage_Ellipse_1.png';
import Ellipse2Image from 'src/assets/images/MainPage_Ellipse_2.png';
import Icon1Image from 'src/assets/images/MainPage_Icon.png';
import Image6Image from 'src/assets/images/MainPage_image_6.png';
import { styled } from '@mui/material/styles';

const MainPage1 = styled('div')({
  backgroundColor: `rgba(246, 246, 246, 1)`,
  borderRadius: `20px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `926px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Background = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `395px`,
  height: `494px`,
  left: `-143px`,
  top: `443px`,
});

const Ellipse1 = styled('img')({
  height: `226px`,
  width: `226px`,
  position: `absolute`,
  left: `169px`,
  top: `268px`,
});

const Ellipse2 = styled('img')({
  height: `226px`,
  width: `226px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Language = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `79px`,
  height: `16px`,
  left: `359px`,
  top: `57px`,
});

const Icon1 = styled('img')({
  height: `10px`,
  width: `6px`,
  position: `absolute`,
  left: `77px`,
  top: `14px`,
});

const English = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilda Display`,
  fontWeight: `400`,
  fontSize: `17px`,
  letterSpacing: `1.02px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `74px`,
  height: `16px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group237458 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `224px`,
  height: `42px`,
  left: `125px`,
  top: `711px`,
});

const Register = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `112px`,
  height: `42px`,
  left: `112px`,
  top: `0px`,
});

const Rectangle1 = styled('div')({
  backgroundColor: `rgba(214, 214, 214, 1)`,
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.05)`,
  borderRadius: `21px`,
  width: `112px`,
  height: `42px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Register1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(21, 21, 22, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilda Display`,
  fontWeight: `400`,
  fontSize: `17px`,
  letterSpacing: `1.02px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `74px`,
  height: `16px`,
  position: `absolute`,
  left: `21px`,
  top: `12px`,
});

const Register2 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `98px`,
  height: `42px`,
  left: `0px`,
  top: `0px`,
});

const Rectangle11 = styled('div')({
  backgroundColor: `rgba(61, 62, 66, 1)`,
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.05)`,
  borderRadius: `21px`,
  width: `98px`,
  height: `42px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const SignIn = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(214, 214, 214, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilda Display`,
  fontWeight: `400`,
  fontSize: `17px`,
  letterSpacing: `1.02px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `64.75px`,
  height: `16px`,
  position: `absolute`,
  left: `18px`,
  top: `12px`,
});

const Image4 = styled('div')({
  width: `411px`,
  height: `287px`,
  position: `absolute`,
  left: `26px`,
  top: `227px`,
});

const SignIn1 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilda Display`,
  fontWeight: `400`,
  fontSize: `32px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `77px`,
  textTransform: `none`,
  width: `401px`,
  height: `141px`,
  position: `absolute`,
  left: `32px`,
  top: `528px`,
});

const Image6 = styled('img')({
  height: `286px`,
  width: `299px`,
  position: `absolute`,
  left: `83px`,
  top: `191px`,
});

function MainPage(props) {
  return (
    <MainPage1 className={props.className}>
      <Background>
        <Ellipse1 src={Ellipse1Image} loading="lazy" alt={'Ellipse 1'} />
        <Ellipse2 src={Ellipse2Image} loading="lazy" alt={'Ellipse 2'} />
      </Background>
      <Language>
        <Icon1 src={Icon1Image} loading="lazy" alt={'Icon'} />
        <English>{`English`}</English>
      </Language>
      <Group237458>
        <Register>
          <Rectangle1></Rectangle1>
          <Register1>{`Register`}</Register1>
        </Register>
        <Register2>
          <Rectangle11></Rectangle11>
          <SignIn>{`Sign In`}</SignIn>
        </Register2>
      </Group237458>
      <Image4></Image4>
      <SignIn1>{`Unified Payment Interface for Crypto`}</SignIn1>
      <Image6 src={Image6Image} loading="lazy" alt={'image 6'} />
    </MainPage1>
  );
}

export default MainPage;
