/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Ellipse2Image from 'src/assets/images/Component8_Ellipse_2.png';
import Line4Image from 'src/assets/images/Component8_Line_4.png';
import CarretRightImage from 'src/assets/images/Component8_Carret_Right.png';
import Ellipse9Image from 'src/assets/images/Component8_Ellipse_9.png';
import VectorImage from 'src/assets/images/Component8_Vector.png';
import EllipseImage from 'src/assets/images/Component8_Ellipse.png';
import Ellipse1Image from 'src/assets/images/Component8_Ellipse_1.png';
import Ellipse3Image from 'src/assets/images/Component8_Ellipse_3.png';
import Ellipse4Image from 'src/assets/images/Component8_Ellipse_4.png';
import Ellipse5Image from 'src/assets/images/Component8_Ellipse_5.png';
import Ellipse6Image from 'src/assets/images/Component8_Ellipse_6.png';
import Ellipse7Image from 'src/assets/images/Component8_Ellipse_7.png';
import Ellipse8Image from 'src/assets/images/Component8_Ellipse_8.png';
import Ellipse10Image from 'src/assets/images/Component8_Ellipse_10.png';
import Ellipse11Image from 'src/assets/images/Component8_Ellipse_11.png';
import Ellipse12Image from 'src/assets/images/Component8_Ellipse_12.png';
import Ellipse13Image from 'src/assets/images/Component8_Ellipse_13.png';
import Ellipse14Image from 'src/assets/images/Component8_Ellipse_14.png';
import Ellipse15Image from 'src/assets/images/Component8_Ellipse_15.png';
import Ellipse16Image from 'src/assets/images/Component8_Ellipse_16.png';
import Ellipse17Image from 'src/assets/images/Component8_Ellipse_17.png';
import Ellipse18Image from 'src/assets/images/Component8_Ellipse_18.png';
import Ellipse19Image from 'src/assets/images/Component8_Ellipse_19.png';
import Ellipse20Image from 'src/assets/images/Component8_Ellipse_20.png';
import Ellipse21Image from 'src/assets/images/Component8_Ellipse_21.png';
import Ellipse22Image from 'src/assets/images/Component8_Ellipse_22.png';
import Ellipse23Image from 'src/assets/images/Component8_Ellipse_23.png';
import Ellipse24Image from 'src/assets/images/Component8_Ellipse_24.png';
import Ellipse25Image from 'src/assets/images/Component8_Ellipse_25.png';
import Ellipse26Image from 'src/assets/images/Component8_Ellipse_26.png';
import Ellipse27Image from 'src/assets/images/Component8_Ellipse_27.png';
import Ellipse28Image from 'src/assets/images/Component8_Ellipse_28.png';
import Ellipse29Image from 'src/assets/images/Component8_Ellipse_29.png';
import Ellipse30Image from 'src/assets/images/Component8_Ellipse_30.png';
import Ellipse31Image from 'src/assets/images/Component8_Ellipse_31.png';
import Ellipse32Image from 'src/assets/images/Component8_Ellipse_32.png';
import Ellipse33Image from 'src/assets/images/Component8_Ellipse_33.png';
import Ellipse34Image from 'src/assets/images/Component8_Ellipse_34.png';
import Ellipse35Image from 'src/assets/images/Component8_Ellipse_35.png';
import Ellipse36Image from 'src/assets/images/Component8_Ellipse_36.png';
import Ellipse37Image from 'src/assets/images/Component8_Ellipse_37.png';
import Ellipse38Image from 'src/assets/images/Component8_Ellipse_38.png';
import Ellipse39Image from 'src/assets/images/Component8_Ellipse_39.png';
import Ellipse40Image from 'src/assets/images/Component8_Ellipse_40.png';
import Ellipse41Image from 'src/assets/images/Component8_Ellipse_41.png';
import Ellipse42Image from 'src/assets/images/Component8_Ellipse_42.png';
// import Ellipse43Image from 'src/assets/images/Component8_Ellipse_43.png';
import Ellipse44Image from 'src/assets/images/Component8_Ellipse_44.png';
import Ellipse45Image from 'src/assets/images/Component8_Ellipse_45.png';
// import Ellipse46Image from 'src/assets/images/Component8_Ellipse_46.png';
import Ellipse47Image from 'src/assets/images/Component8_Ellipse_47.png';
import Ellipse48Image from 'src/assets/images/Component8_Ellipse_48.png';
import Ellipse49Image from 'src/assets/images/Component8_Ellipse_49.png';
import Ellipse50Image from 'src/assets/images/Component8_Ellipse_50.png';
import Ellipse51Image from 'src/assets/images/Component8_Ellipse_51.png';
import Ellipse52Image from 'src/assets/images/Component8_Ellipse_52.png';
import Ellipse53Image from 'src/assets/images/Component8_Ellipse_53.png';
import Ellipse54Image from 'src/assets/images/Component8_Ellipse_54.png';
import Ellipse55Image from 'src/assets/images/Component8_Ellipse_55.png';
import BoutonSignInImage from 'src/assets/images/Component8_Bouton_Sign_In.png';
import CircleErrorImage from 'src/assets/images/Component8_circle_error.png';
import { styled } from '@mui/material/styles';
// import ArrowUpRight from 'src/components/ArrowUpRight/ArrowUpRight';
// import ArrowDownRight from 'src/components/ArrowDownRight/ArrowDownRight';

const Component81 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `926px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

// const ArrowUpRight1 = styled(ArrowUpRight)(({ theme }) => ({
//   width: `46px`,
//   height: `41px`,
//   position: `absolute`,
//   left: `71px`,
//   top: `416px`,
// }));

// const ArrowDownRight1 = styled(ArrowDownRight)(({ theme }) => ({
//   width: `46px`,
//   height: `41px`,
//   position: `absolute`,
//   left: `71px`,
//   top: `361px`,
// }));

const PaymentSuccessful = styled('div')({
  backgroundColor: `rgba(28, 23, 23, 1)`,
  borderRadius: `20px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `474px`,
  height: `926px`,
  left: `0px`,
  top: `0px`,
  overflow: `hidden`,
});

const Background = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `226px`,
  height: `226px`,
  left: `-402px`,
  top: `908px`,
});

const Ellipse2 = styled('img')({
  height: `226px`,
  width: `226px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const SignIn = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `700`,
  fontSize: `32px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `77px`,
  textTransform: `none`,
  width: `290px`,
  height: `67px`,
  position: `absolute`,
  left: `69px`,
  top: `28px`,
});

const Line4 = styled('img')({
  height: `0px`,
  width: `340px`,
  position: `absolute`,
  left: `784px`,
  top: `516px`,
});

const CarretRight = styled('img')({
  height: `48px`,
  width: `45px`,
  position: `absolute`,
  left: `109px`,
  top: `144px`,
});

const PaymentSuccessful1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `2px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  width: `340px`,
  position: `absolute`,
  left: `103px`,
  top: `369px`,
});

const Line2 = styled('div')({
  border: `1px solid rgba(223, 223, 223, 1)`,
  width: `120px`,
  height: `0px`,
  position: `absolute`,
  left: `69px`,
  top: `92px`,
});

const Frame21 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `283px`,
  height: `123px`,
  left: `84px`,
  top: `207px`,
});

const SuccessIconComponent = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `123px`,
  width: `123px`,
  margin: `0px`,
});

const Ellipse9 = styled('img')({
  height: `123px`,
  width: `123px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector = styled('img')({
  height: `38.13px`,
  width: `55.46px`,
  position: `absolute`,
  left: `36px`,
  top: `41px`,
});

const Message = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  height: `59px`,
  width: `294px`,
  margin: `30px 0px 0px 0px`,
});

const YourTransactionHasSu = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 0.6)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `340px`,
  position: `absolute`,
  left: `64px`,
  top: `441px`,
});

const Confetti = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `474px`,
  height: `830px`,
  left: `0px`,
  top: `96px`,
});

const Rectangle = styled('div')({
  backgroundColor: `rgba(236, 180, 60, 1)`,
  width: `31.2px`,
  height: `4.85px`,
  position: `absolute`,
  left: `338px`,
  top: `91px`,
});

const Rectangle1 = styled('div')({
  backgroundColor: `rgba(253, 165, 165, 0.85)`,
  width: `11.67px`,
  height: `8.61px`,
  position: `absolute`,
  left: `83px`,
  top: `292px`,
});

const Rectangle2 = styled('div')({
  backgroundColor: `rgba(86, 184, 165, 0.75)`,
  width: `17.98px`,
  height: `7.57px`,
  position: `absolute`,
  left: `344px`,
  top: `518px`,
});

const Rectangle3 = styled('div')({
  backgroundColor: `rgba(86, 184, 165, 0.85)`,
  width: `15.85px`,
  height: `6.69px`,
  position: `absolute`,
  left: `426px`,
  top: `237px`,
});

const Rectangle4 = styled('div')({
  backgroundColor: `rgba(61, 189, 150, 0.35)`,
  width: `13.82px`,
  height: `8.21px`,
  position: `absolute`,
  left: `98px`,
  top: `554px`,
});

const Rectangle5 = styled('div')({
  backgroundColor: `rgba(236, 180, 60, 0.35)`,
  width: `8.91px`,
  height: `3.8px`,
  position: `absolute`,
  left: `106px`,
  top: `350px`,
});

const Rectangle6 = styled('div')({
  backgroundColor: `rgba(86, 184, 165, 1)`,
  width: `17.42px`,
  height: `3.77px`,
  position: `absolute`,
  left: `35px`,
  top: `358px`,
});

const Rectangle7 = styled('div')({
  backgroundColor: `rgba(86, 184, 165, 0.35)`,
  width: `14.64px`,
  height: `7.73px`,
  position: `absolute`,
  left: `176px`,
  top: `266px`,
});

const Rectangle8 = styled('div')({
  backgroundColor: `rgba(86, 184, 165, 0.9)`,
  width: `39.59px`,
  height: `4.65px`,
  position: `absolute`,
  left: `287px`,
  top: `32px`,
});

const Rectangle9 = styled('div')({
  backgroundColor: `rgba(61, 189, 150, 0.65)`,
  width: `9.11px`,
  height: `7.17px`,
  position: `absolute`,
  left: `131px`,
  top: `14px`,
});

const Rectangle10 = styled('div')({
  backgroundColor: `rgba(61, 189, 150, 1)`,
  width: `23.31px`,
  height: `7.49px`,
  position: `absolute`,
  left: `418px`,
  top: `367px`,
});

const Rectangle11 = styled('div')({
  backgroundColor: `rgba(236, 180, 60, 1)`,
  width: `26.86px`,
  height: `3.78px`,
  position: `absolute`,
  left: `170px`,
  top: `89px`,
});

const Rectangle12 = styled('div')({
  backgroundColor: `rgba(86, 184, 165, 0.45)`,
  width: `34.84px`,
  height: `6.55px`,
  position: `absolute`,
  left: `141px`,
  top: `616px`,
});

const Rectangle13 = styled('div')({
  backgroundColor: `rgba(253, 165, 165, 0.65)`,
  width: `31.18px`,
  height: `3.77px`,
  position: `absolute`,
  left: `441px`,
  top: `507px`,
});

const Rectangle14 = styled('div')({
  backgroundColor: `rgba(236, 180, 60, 0.85)`,
  width: `34.36px`,
  height: `3.76px`,
  position: `absolute`,
  left: `415px`,
  top: `127px`,
});

const Rectangle15 = styled('div')({
  backgroundColor: `rgba(61, 189, 150, 0.9)`,
  width: `37.75px`,
  height: `3.88px`,
  position: `absolute`,
  left: `151px`,
  top: `257px`,
});

const Rectangle16 = styled('div')({
  backgroundColor: `rgba(253, 165, 165, 0.85)`,
  width: `16.08px`,
  height: `8.03px`,
  position: `absolute`,
  left: `436px`,
  top: `644px`,
});

const Rectangle17 = styled('div')({
  backgroundColor: `rgba(61, 189, 150, 0.9)`,
  width: `14.5px`,
  height: `7.7px`,
  position: `absolute`,
  left: `37px`,
  top: `132px`,
});

const Rectangle18 = styled('div')({
  backgroundColor: `rgba(86, 184, 165, 0.75)`,
  width: `30.72px`,
  height: `6.09px`,
  position: `absolute`,
  left: `382px`,
  top: `531px`,
});

const Rectangle19 = styled('div')({
  backgroundColor: `rgba(86, 184, 165, 0.6)`,
  width: `21.29px`,
  height: `5.99px`,
  position: `absolute`,
  left: `32px`,
  top: `746px`,
});

const Rectangle20 = styled('div')({
  backgroundColor: `rgba(61, 189, 150, 0.85)`,
  width: `13.65px`,
  height: `6.63px`,
  position: `absolute`,
  left: `392px`,
  top: `703px`,
});

const Rectangle21 = styled('div')({
  backgroundColor: `rgba(236, 180, 60, 0.75)`,
  width: `10.27px`,
  height: `7.61px`,
  position: `absolute`,
  left: `212px`,
  top: `280px`,
});

const Rectangle22 = styled('div')({
  backgroundColor: `rgba(236, 180, 60, 0.85)`,
  width: `28.5px`,
  height: `6.15px`,
  position: `absolute`,
  left: `122px`,
  top: `40px`,
});

const Rectangle23 = styled('div')({
  backgroundColor: `rgba(253, 165, 165, 0.85)`,
  width: `23.55px`,
  height: `7.8px`,
  position: `absolute`,
  left: `234px`,
  top: `518px`,
});

const Rectangle24 = styled('div')({
  backgroundColor: `rgba(86, 184, 165, 0.75)`,
  width: `33.63px`,
  height: `4.37px`,
  position: `absolute`,
  left: `404px`,
  top: `256px`,
});

const Rectangle25 = styled('div')({
  backgroundColor: `rgba(253, 165, 165, 0.35)`,
  width: `9.75px`,
  height: `6.37px`,
  position: `absolute`,
  left: `369px`,
  top: `808px`,
});

const Rectangle26 = styled('div')({
  backgroundColor: `rgba(236, 180, 60, 0.6)`,
  width: `8.97px`,
  height: `8.17px`,
  position: `absolute`,
  left: `133px`,
  top: `791px`,
});

const Rectangle27 = styled('div')({
  backgroundColor: `rgba(253, 165, 165, 1)`,
  width: `15.38px`,
  height: `7.7px`,
  position: `absolute`,
  left: `395px`,
  top: `496px`,
});

const Rectangle28 = styled('div')({
  backgroundColor: `rgba(86, 184, 165, 0.35)`,
  width: `24.92px`,
  height: `8.57px`,
  position: `absolute`,
  left: `439px`,
  top: `244px`,
});

const Rectangle29 = styled('div')({
  backgroundColor: `rgba(61, 189, 150, 0.6)`,
  width: `8.07px`,
  height: `8.23px`,
  position: `absolute`,
  left: `33px`,
  top: `490px`,
});

const Rectangle30 = styled('div')({
  backgroundColor: `rgba(61, 189, 150, 0.6)`,
  width: `27.53px`,
  height: `6.15px`,
  position: `absolute`,
  left: `495px`,
  top: `360px`,
});

const Rectangle31 = styled('div')({
  backgroundColor: `rgba(236, 180, 60, 0.85)`,
  width: `26.54px`,
  height: `6.53px`,
  position: `absolute`,
  left: `439px`,
  top: `316px`,
});

const Rectangle32 = styled('div')({
  backgroundColor: `rgba(236, 180, 60, 0.45)`,
  width: `12.81px`,
  height: `4.51px`,
  position: `absolute`,
  left: `444px`,
  top: `108px`,
});

const Rectangle33 = styled('div')({
  backgroundColor: `rgba(86, 184, 165, 0.75)`,
  width: `5.7px`,
  height: `5.58px`,
  position: `absolute`,
  left: `210px`,
  top: `6px`,
});

const Rectangle34 = styled('div')({
  backgroundColor: `rgba(236, 180, 60, 0.85)`,
  width: `36.98px`,
  height: `3.98px`,
  position: `absolute`,
  left: `383px`,
  top: `247px`,
});

const Rectangle35 = styled('div')({
  backgroundColor: `rgba(253, 165, 165, 0.75)`,
  width: `30.6px`,
  height: `4.4px`,
  position: `absolute`,
  left: `455px`,
  top: `508px`,
});

const Rectangle36 = styled('div')({
  backgroundColor: `rgba(253, 165, 165, 0.45)`,
  width: `5.89px`,
  height: `6.49px`,
  position: `absolute`,
  left: `224px`,
  top: `675px`,
});

const Rectangle37 = styled('div')({
  backgroundColor: `rgba(253, 165, 165, 0.45)`,
  width: `33.21px`,
  height: `7.34px`,
  position: `absolute`,
  left: `45px`,
  top: `646px`,
});

const Rectangle38 = styled('div')({
  backgroundColor: `rgba(236, 180, 60, 0.85)`,
  width: `34.15px`,
  height: `8.35px`,
  position: `absolute`,
  left: `70px`,
  top: `152px`,
});

const Rectangle39 = styled('div')({
  backgroundColor: `rgba(61, 189, 150, 0.65)`,
  width: `6.86px`,
  height: `8.5px`,
  position: `absolute`,
  left: `139px`,
  top: `211px`,
});

const Rectangle40 = styled('div')({
  backgroundColor: `rgba(86, 184, 165, 0.9)`,
  width: `21.31px`,
  height: `3.85px`,
  position: `absolute`,
  left: `28px`,
  top: `229px`,
});

const Rectangle41 = styled('div')({
  backgroundColor: `rgba(61, 189, 150, 0.6)`,
  width: `26.9px`,
  height: `6.42px`,
  position: `absolute`,
  left: `43px`,
  top: `342px`,
});

const Rectangle42 = styled('div')({
  backgroundColor: `rgba(236, 180, 60, 0.75)`,
  width: `11.04px`,
  height: `8.22px`,
  position: `absolute`,
  left: `343px`,
  top: `29px`,
});

const Rectangle43 = styled('div')({
  backgroundColor: `rgba(86, 184, 165, 0.35)`,
  width: `10px`,
  height: `6.22px`,
  position: `absolute`,
  left: `165px`,
  top: `140px`,
});

const Rectangle44 = styled('div')({
  backgroundColor: `rgba(253, 165, 165, 0.85)`,
  width: `16.26px`,
  height: `8.76px`,
  position: `absolute`,
  left: `342px`,
  top: `174px`,
});

const Rectangle45 = styled('div')({
  backgroundColor: `rgba(86, 184, 165, 0.65)`,
  width: `27.87px`,
  height: `8.72px`,
  position: `absolute`,
  left: `107px`,
  top: `715px`,
});

const Rectangle46 = styled('div')({
  backgroundColor: `rgba(61, 189, 150, 0.85)`,
  width: `14.36px`,
  height: `8.41px`,
  position: `absolute`,
  left: `261px`,
  top: `572px`,
});

const Rectangle47 = styled('div')({
  backgroundColor: `rgba(236, 180, 60, 0.75)`,
  width: `23.89px`,
  height: `8.03px`,
  position: `absolute`,
  left: `133px`,
  top: `830px`,
});

const Rectangle48 = styled('div')({
  backgroundColor: `rgba(86, 184, 165, 1)`,
  width: `28.13px`,
  height: `3.93px`,
  position: `absolute`,
  left: `47px`,
  top: `159px`,
});

const Rectangle49 = styled('div')({
  backgroundColor: `rgba(61, 189, 150, 0.35)`,
  width: `8.07px`,
  height: `9.23px`,
  position: `absolute`,
  left: `295px`,
  top: `148px`,
});

const Rectangle50 = styled('div')({
  backgroundColor: `rgba(236, 180, 60, 1)`,
  width: `29.24px`,
  height: `6.53px`,
  position: `absolute`,
  left: `350px`,
  top: `195px`,
});

const Rectangle51 = styled('div')({
  backgroundColor: `rgba(236, 180, 60, 0.6)`,
  width: `18.67px`,
  height: `5.44px`,
  position: `absolute`,
  left: `382px`,
  top: `364px`,
});

const Rectangle52 = styled('div')({
  backgroundColor: `rgba(253, 165, 165, 0.6)`,
  width: `22.46px`,
  height: `4.72px`,
  position: `absolute`,
  left: `110px`,
  top: `677px`,
});

const Rectangle53 = styled('div')({
  backgroundColor: `rgba(253, 165, 165, 0.45)`,
  width: `33.75px`,
  height: `7.24px`,
  position: `absolute`,
  left: `401px`,
  top: `36px`,
});

const Ellipse = styled('img')({
  height: `4.95px`,
  width: `5.96px`,
  position: `absolute`,
  left: `77px`,
  top: `592px`,
});

const Ellipse1 = styled('img')({
  height: `11.99px`,
  width: `14.42px`,
  position: `absolute`,
  left: `215px`,
  top: `105px`,
});

const Ellipse3 = styled('img')({
  height: `11.99px`,
  width: `14.42px`,
  position: `absolute`,
  left: `88px`,
  top: `472px`,
});

const Ellipse4 = styled('img')({
  height: `10.23px`,
  width: `12.3px`,
  position: `absolute`,
  left: `41px`,
  top: `192px`,
});

const Ellipse5 = styled('img')({
  height: `11.11px`,
  width: `13.36px`,
  position: `absolute`,
  left: `328px`,
  top: `169px`,
});

const Ellipse6 = styled('img')({
  height: `4.07px`,
  width: `4.9px`,
  position: `absolute`,
  left: `346px`,
  top: `526px`,
});

const Ellipse7 = styled('img')({
  height: `5.83px`,
  width: `7.01px`,
  position: `absolute`,
  left: `441px`,
  top: `688px`,
});

const Ellipse8 = styled('img')({
  height: `4.95px`,
  width: `5.96px`,
  position: `absolute`,
  left: `265px`,
  top: `289px`,
});

const Ellipse10 = styled('img')({
  height: `6.71px`,
  width: `8.07px`,
  position: `absolute`,
  left: `245px`,
  top: `684px`,
});

const Ellipse11 = styled('img')({
  height: `8.47px`,
  width: `10.19px`,
  position: `absolute`,
  left: `115px`,
  top: `782px`,
});

const Ellipse12 = styled('img')({
  height: `8.47px`,
  width: `10.19px`,
  position: `absolute`,
  left: `139px`,
  top: `647px`,
});

const Ellipse13 = styled('img')({
  height: `8.47px`,
  width: `10.19px`,
  position: `absolute`,
  left: `62px`,
  top: `321px`,
});

const Ellipse14 = styled('img')({
  height: `9.35px`,
  width: `11.25px`,
  position: `absolute`,
  left: `350px`,
  top: `45px`,
});

const Ellipse15 = styled('img')({
  height: `6.71px`,
  width: `8.07px`,
  position: `absolute`,
  left: `140px`,
  top: `393px`,
});

const Ellipse16 = styled('img')({
  height: `5.83px`,
  width: `7.01px`,
  position: `absolute`,
  left: `388px`,
  top: `343px`,
});

const Ellipse17 = styled('img')({
  height: `5.83px`,
  width: `7.01px`,
  position: `absolute`,
  left: `388px`,
  top: `151px`,
});

const Ellipse18 = styled('img')({
  height: `10.23px`,
  width: `12.3px`,
  position: `absolute`,
  left: `45px`,
  top: `248px`,
});

const Ellipse19 = styled('img')({
  height: `10.23px`,
  width: `12.3px`,
  position: `absolute`,
  left: `89px`,
  top: `700px`,
});

const Ellipse20 = styled('img')({
  height: `11.99px`,
  width: `14.42px`,
  position: `absolute`,
  left: `313px`,
  top: `649px`,
});

const Ellipse21 = styled('img')({
  height: `11.99px`,
  width: `14.42px`,
  position: `absolute`,
  left: `122px`,
  top: `743px`,
});

const Ellipse22 = styled('img')({
  height: `4.95px`,
  width: `5.96px`,
  position: `absolute`,
  left: `398px`,
  top: `465px`,
});

const Ellipse23 = styled('img')({
  height: `5.83px`,
  width: `7.01px`,
  position: `absolute`,
  left: `171px`,
  top: `5px`,
});

const Ellipse24 = styled('img')({
  height: `4.95px`,
  width: `5.96px`,
  position: `absolute`,
  left: `68px`,
  top: `817px`,
});

const Ellipse25 = styled('img')({
  height: `6.71px`,
  width: `8.07px`,
  position: `absolute`,
  left: `461px`,
  top: `439px`,
});

const Ellipse26 = styled('img')({
  height: `4.07px`,
  width: `4.9px`,
  position: `absolute`,
  left: `362px`,
  top: `98px`,
});

const Ellipse27 = styled('img')({
  height: `11.99px`,
  width: `14.42px`,
  position: `absolute`,
  left: `65px`,
  top: `65px`,
});

const Ellipse28 = styled('img')({
  height: `5.83px`,
  width: `7.01px`,
  position: `absolute`,
  left: `157px`,
  top: `138px`,
});

const Ellipse29 = styled('img')({
  height: `4.07px`,
  width: `4.9px`,
  position: `absolute`,
  left: `280px`,
  top: `225px`,
});

const Ellipse30 = styled('img')({
  height: `5.83px`,
  width: `7.01px`,
  position: `absolute`,
  left: `423px`,
  top: `460px`,
});

const Ellipse31 = styled('img')({
  height: `10.23px`,
  width: `12.3px`,
  position: `absolute`,
  left: `304px`,
  top: `811px`,
});

const Ellipse32 = styled('img')({
  height: `5.83px`,
  width: `7.01px`,
  position: `absolute`,
  left: `186px`,
  top: `133px`,
});

const Ellipse33 = styled('img')({
  height: `11.11px`,
  width: `13.36px`,
  position: `absolute`,
  left: `144px`,
  top: `420px`,
});

const Ellipse34 = styled('img')({
  height: `11.99px`,
  width: `14.42px`,
  position: `absolute`,
  left: `273px`,
  top: `772px`,
});

const Ellipse35 = styled('img')({
  height: `11.11px`,
  width: `13.36px`,
  position: `absolute`,
  left: `289px`,
  top: `389px`,
});

const Ellipse36 = styled('img')({
  height: `11.11px`,
  width: `13.36px`,
  position: `absolute`,
  left: `150px`,
  top: `559px`,
});

const Ellipse37 = styled('img')({
  height: `8.47px`,
  width: `10.19px`,
  position: `absolute`,
  left: `102px`,
  top: `641px`,
});

const Ellipse38 = styled('img')({
  height: `5.83px`,
  width: `7.01px`,
  position: `absolute`,
  left: `334px`,
  top: `806px`,
});

const Ellipse39 = styled('img')({
  height: `7.59px`,
  width: `9.13px`,
  position: `absolute`,
  left: `196px`,
  top: `491px`,
});

const Ellipse40 = styled('img')({
  height: `7.59px`,
  width: `9.13px`,
  position: `absolute`,
  left: `458px`,
  top: `168px`,
});

const Ellipse41 = styled('img')({
  height: `11.99px`,
  width: `14.42px`,
  position: `absolute`,
  left: `190px`,
  top: `398px`,
});

const Ellipse42 = styled('img')({
  height: `6.71px`,
  width: `8.07px`,
  position: `absolute`,
  left: `448px`,
  top: `800px`,
});

const Ellipse43 = styled('img')({
  height: `9.35px`,
  width: `11.25px`,
  position: `absolute`,
  left: `271px`,
  top: `116px`,
});

const Ellipse44 = styled('img')({
  height: `10.23px`,
  width: `12.3px`,
  position: `absolute`,
  left: `404px`,
  top: `535px`,
});

const Ellipse45 = styled('img')({
  height: `10.23px`,
  width: `12.3px`,
  position: `absolute`,
  left: `441px`,
  top: `417px`,
});

const Ellipse46 = styled('img')({
  height: `7.59px`,
  width: `9.13px`,
  position: `absolute`,
  left: `62px`,
  top: `381px`,
});

const Ellipse47 = styled('img')({
  height: `4.95px`,
  width: `5.96px`,
  position: `absolute`,
  left: `132px`,
  top: `594px`,
});

const Ellipse48 = styled('img')({
  height: `8.47px`,
  width: `10.19px`,
  position: `absolute`,
  left: `190px`,
  top: `476px`,
});

const Ellipse49 = styled('img')({
  height: `4.07px`,
  width: `4.9px`,
  position: `absolute`,
  left: `196px`,
  top: `40px`,
});

const Ellipse50 = styled('img')({
  height: `11.99px`,
  width: `14.42px`,
  position: `absolute`,
  left: `334px`,
  top: `12px`,
});

const Ellipse51 = styled('img')({
  height: `10.23px`,
  width: `12.3px`,
  position: `absolute`,
  left: `268px`,
  top: `781px`,
});

const Ellipse52 = styled('img')({
  height: `4.95px`,
  width: `5.96px`,
  position: `absolute`,
  left: `132px`,
  top: `154px`,
});

const Ellipse53 = styled('img')({
  height: `7.59px`,
  width: `9.13px`,
  position: `absolute`,
  left: `130px`,
  top: `9px`,
});

const Ellipse54 = styled('img')({
  height: `10.23px`,
  width: `12.3px`,
  position: `absolute`,
  left: `34px`,
  top: `373px`,
});

const Ellipse55 = styled('img')({
  height: `11.11px`,
  width: `13.36px`,
  position: `absolute`,
  left: `310px`,
  top: `709px`,
});

const BoutonSignIn = styled('img')({
  height: `77px`,
  width: `400px`,
  position: `absolute`,
  left: `25px`,
  top: `559px`,
});

const CircleError = styled('img')({
  height: `48px`,
  width: `49px`,
  position: `absolute`,
  left: `397px`,
  top: `48px`,
});

function TransactionSuccessful(props) {
  return (
    <Component81 className={props.className}>
      {/* <ArrowUpRight1 /> */}
      {/* <ArrowDownRight1 /> */}
      <PaymentSuccessful>
        <Background>
          <Ellipse2 src={Ellipse2Image} loading="lazy" alt={'Ellipse 2'} />
        </Background>
        <SignIn>{`Payment`}</SignIn>
        <Line4 src={Line4Image} loading="lazy" alt={'Line 4'} />
        <CarretRight
          src={CarretRightImage}
          loading="lazy"
          alt={'Carret_Right'}
        />
        <PaymentSuccessful1>{`Payment Successful!`}</PaymentSuccessful1>
        <Line2></Line2>
        <Frame21>
          <SuccessIconComponent>
            <Ellipse9 src={Ellipse9Image} loading="lazy" alt={'Ellipse 9'} />
            <Vector src={VectorImage} loading="lazy" alt={'Vector'} />
          </SuccessIconComponent>
          <Message></Message>
        </Frame21>
        <YourTransactionHasSu>
          {`Your transaction has successfully been completed. Click transaction details to check details on-chain.
We value you!`}
        </YourTransactionHasSu>
        <Confetti>
          <Rectangle></Rectangle>
          <Rectangle1></Rectangle1>
          <Rectangle2></Rectangle2>
          <Rectangle3></Rectangle3>
          <Rectangle4></Rectangle4>
          <Rectangle5></Rectangle5>
          <Rectangle6></Rectangle6>
          <Rectangle7></Rectangle7>
          <Rectangle8></Rectangle8>
          <Rectangle9></Rectangle9>
          <Rectangle10></Rectangle10>
          <Rectangle11></Rectangle11>
          <Rectangle12></Rectangle12>
          <Rectangle13></Rectangle13>
          <Rectangle14></Rectangle14>
          <Rectangle15></Rectangle15>
          <Rectangle16></Rectangle16>
          <Rectangle17></Rectangle17>
          <Rectangle18></Rectangle18>
          <Rectangle19></Rectangle19>
          <Rectangle20></Rectangle20>
          <Rectangle21></Rectangle21>
          <Rectangle22></Rectangle22>
          <Rectangle23></Rectangle23>
          <Rectangle24></Rectangle24>
          <Rectangle25></Rectangle25>
          <Rectangle26></Rectangle26>
          <Rectangle27></Rectangle27>
          <Rectangle28></Rectangle28>
          <Rectangle29></Rectangle29>
          <Rectangle30></Rectangle30>
          <Rectangle31></Rectangle31>
          <Rectangle32></Rectangle32>
          <Rectangle33></Rectangle33>
          <Rectangle34></Rectangle34>
          <Rectangle35></Rectangle35>
          <Rectangle36></Rectangle36>
          <Rectangle37></Rectangle37>
          <Rectangle38></Rectangle38>
          <Rectangle39></Rectangle39>
          <Rectangle40></Rectangle40>
          <Rectangle41></Rectangle41>
          <Rectangle42></Rectangle42>
          <Rectangle43></Rectangle43>
          <Rectangle44></Rectangle44>
          <Rectangle45></Rectangle45>
          <Rectangle46></Rectangle46>
          <Rectangle47></Rectangle47>
          <Rectangle48></Rectangle48>
          <Rectangle49></Rectangle49>
          <Rectangle50></Rectangle50>
          <Rectangle51></Rectangle51>
          <Rectangle52></Rectangle52>
          <Rectangle53></Rectangle53>
          <Ellipse src={EllipseImage} loading="lazy" alt={'Ellipse'} />
          <Ellipse1 src={Ellipse1Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse3 src={Ellipse3Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse4 src={Ellipse4Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse5 src={Ellipse5Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse6 src={Ellipse6Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse7 src={Ellipse7Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse8 src={Ellipse8Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse10 src={Ellipse10Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse11 src={Ellipse11Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse12 src={Ellipse12Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse13 src={Ellipse13Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse14 src={Ellipse14Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse15 src={Ellipse15Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse16 src={Ellipse16Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse17 src={Ellipse17Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse18 src={Ellipse18Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse19 src={Ellipse19Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse20 src={Ellipse20Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse21 src={Ellipse21Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse22 src={Ellipse22Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse23 src={Ellipse23Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse24 src={Ellipse24Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse25 src={Ellipse25Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse26 src={Ellipse26Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse27 src={Ellipse27Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse28 src={Ellipse28Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse29 src={Ellipse29Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse30 src={Ellipse30Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse31 src={Ellipse31Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse32 src={Ellipse32Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse33 src={Ellipse33Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse34 src={Ellipse34Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse35 src={Ellipse35Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse36 src={Ellipse36Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse37 src={Ellipse37Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse38 src={Ellipse38Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse39 src={Ellipse39Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse40 src={Ellipse40Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse41 src={Ellipse41Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse42 src={Ellipse42Image} loading="lazy" alt={'Ellipse'} />
          {/* <Ellipse43 src={Ellipse43Image} loading="lazy" alt={'Ellipse'} /> */}
          <Ellipse44 src={Ellipse44Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse45 src={Ellipse45Image} loading="lazy" alt={'Ellipse'} />
          {/* <Ellipse46 src={Ellipse46Image} loading="lazy" alt={'Ellipse'} /> */}
          <Ellipse47 src={Ellipse47Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse48 src={Ellipse48Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse49 src={Ellipse49Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse50 src={Ellipse50Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse51 src={Ellipse51Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse52 src={Ellipse52Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse53 src={Ellipse53Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse54 src={Ellipse54Image} loading="lazy" alt={'Ellipse'} />
          <Ellipse55 src={Ellipse55Image} loading="lazy" alt={'Ellipse'} />
        </Confetti>
        <BoutonSignIn
          src={BoutonSignInImage}
          loading="lazy"
          alt={'Bouton Sign In'}
        />
        <CircleError
          src={CircleErrorImage}
          loading="lazy"
          alt={'circle-error'}
        />
      </PaymentSuccessful>
    </Component81>
  );
}

export default TransactionSuccessful;
