/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Ellipse2Image from 'src/assets/images/Component4_Ellipse_2.png';
import Line4Image from 'src/assets/images/Component4_Line_4.png';
import VectorImage from 'src/assets/images/Component4_Vector.png';
import Vector1Image from 'src/assets/images/Component4_Vector_1.png';
import Vector2Image from 'src/assets/images/Component4_Vector_2.png';
import Vector3Image from 'src/assets/images/Component4_Vector_3.png';
import Vector4Image from 'src/assets/images/Component4_Vector_4.png';
import Vector5Image from 'src/assets/images/Component4_Vector_5.png';
import Vector6Image from 'src/assets/images/Component4_Vector_6.png';
import Vector7Image from 'src/assets/images/Component4_Vector_7.png';
import Vector8Image from 'src/assets/images/Component4_Vector_8.png';
import Vector9Image from 'src/assets/images/Component4_Vector_9.png';
import Vector10Image from 'src/assets/images/Component4_Vector_10.png';
import Vector11Image from 'src/assets/images/Component4_Vector_11.png';
import Vector12Image from 'src/assets/images/Component4_Vector_12.png';
import Vector13Image from 'src/assets/images/Component4_Vector_13.png';
import Vector14Image from 'src/assets/images/Component4_Vector_14.png';
import Ellipse3Image from 'src/assets/images/Component4_Ellipse_3.png';
import BoutonSignInImage from 'src/assets/images/Component4_Bouton_Sign_In.png';
import BoutonSignIn1Image from 'src/assets/images/Component4_Bouton_Sign_In_1.png';
import BoutonSignIn2Image from 'src/assets/images/Component4_Bouton_Sign_In_2.png';
import DragImage from 'src/assets/images/Component4_drag.png';
import { styled } from '@mui/material/styles';
// import ArrowUpRight from 'src/components/ArrowUpRight/ArrowUpRight';
// import ArrowDownRight from 'src/components/ArrowDownRight/ArrowDownRight';

const Component41 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `926px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

// const ArrowUpRight1 = styled(ArrowUpRight)(({ theme }) => ({
//   width: `46px`,
//   height: `41px`,
//   position: `absolute`,
//   left: `39px`,
//   top: `416px`,
// }));

// const ArrowDownRight1 = styled(ArrowDownRight)(({ theme }) => ({
//   width: `46px`,
//   height: `41px`,
//   position: `absolute`,
//   left: `39px`,
//   top: `361px`,
// }));

const WalletPortfolio = styled('div')({
  backgroundColor: `rgba(28, 23, 23, 1)`,
  borderRadius: `20px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `474px`,
  height: `926px`,
  left: `0px`,
  top: `0px`,
  overflow: `hidden`,
});

const Background = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `226px`,
  height: `226px`,
  left: `-402px`,
  top: `908px`,
});

const Ellipse2 = styled('img')({
  height: `226px`,
  width: `226px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group237458 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `410px`,
  height: `722px`,
  left: `35px`,
  top: `85px`,
});

const Group237456 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `410px`,
  height: `722px`,
  left: `0px`,
  top: `0px`,
});

const Forms = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `410px`,
  height: `722px`,
  left: `0px`,
  top: `0px`,
});

const ForgetPasswordText = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `410px`,
  height: `670px`,
  left: `0px`,
  top: `52px`,
});

const Q1015Bnb = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `2px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  width: `118px`,
  position: `absolute`,
  left: `203px`,
  top: `224px`,
});

const Bnb226692Span1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `2px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
});

const Bnb226692Span2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(199, 199, 199, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `1.5px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
});

const Bnb226692Span3 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(47, 250, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `1.5px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
});

const Bnb226692 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `nullpx`,
  letterSpacing: `NaNpx`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  width: `125px`,
  position: `absolute`,
  left: `33px`,
  top: `218px`,
});

const Mohit = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `2px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  width: `98px`,
  position: `absolute`,
  left: `312px`,
  top: `105px`,
});

const CryptoBalance12669Span1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `2px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
});

const CryptoBalance12669Span2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(199, 199, 199, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `1.5px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
});

const CryptoBalance12669 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `nullpx`,
  letterSpacing: `NaNpx`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  width: `190px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Eth1210043Span1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `2px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
});

const Eth1210043Span2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(199, 199, 199, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `1.5px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
});

const Eth1210043Span3 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(47, 250, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `1.5px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
});

const Eth1210043 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `nullpx`,
  letterSpacing: `NaNpx`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  width: `125px`,
  position: `absolute`,
  left: `33px`,
  top: `308px`,
});

const Dot09096Span1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `2px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
});

const Dot09096Span2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(199, 199, 199, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `1.5px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
});

const Dot09096Span3 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(250, 28, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `1.5px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
});

const Dot09096 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `nullpx`,
  letterSpacing: `NaNpx`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  width: `125px`,
  position: `absolute`,
  left: `33px`,
  top: `618px`,
});

const Usdc10043Span1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `2px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
});

const Usdc10043Span2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(199, 199, 199, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `1.5px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
});

const Usdc10043Span3 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(47, 250, 14, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `1.5px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
});

const Usdc10043 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `nullpx`,
  letterSpacing: `NaNpx`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  width: `125px`,
  position: `absolute`,
  left: `33px`,
  top: `518px`,
});

const Xrp11013Span1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `2px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
});

const Xrp11013Span2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(199, 199, 199, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `1.5px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
});

const Xrp11013Span3 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(224, 42, 31, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `1.5px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
});

const Xrp11013 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `nullpx`,
  letterSpacing: `NaNpx`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  width: `125px`,
  position: `absolute`,
  left: `33px`,
  top: `417px`,
});

const Q125Dot = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `2px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  width: `150px`,
  position: `absolute`,
  left: `188px`,
  top: `619px`,
});

const Q2226Eth = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `2px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  width: `124px`,
  position: `absolute`,
  left: `188px`,
  top: `302px`,
});

const Q10026Xrp = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `2px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  width: `153px`,
  position: `absolute`,
  left: `181px`,
  top: `419px`,
});

const Q10026Usdc = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `2px`,
  textDecoration: `none`,
  lineHeight: `25px`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  width: `153px`,
  position: `absolute`,
  left: `168px`,
  top: `526px`,
});

const Line = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `120px`,
  height: `0px`,
  left: `1px`,
  top: `0px`,
});

const Line1 = styled('div')({
  border: `1px solid rgba(223, 223, 223, 1)`,
  width: `120px`,
  height: `0px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Line4 = styled('img')({
  height: `0px`,
  width: `340px`,
  position: `absolute`,
  left: `784px`,
  top: `516px`,
});

const IconBinanceCoinCrypt = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `33px`,
  height: `33px`,
  left: `13px`,
  top: `370px`,
});

const Group = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `33px`,
  height: `33px`,
  left: `0px`,
  top: `0px`,
});

const Vector = styled('img')({
  height: `33px`,
  width: `33px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector1 = styled('img')({
  height: `20.63px`,
  width: `20.63px`,
  position: `absolute`,
  left: `6px`,
  top: `6px`,
});

const IconEthereumCryptocu = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `33px`,
  height: `33px`,
  left: `15px`,
  top: `462px`,
});

const Group1 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `33px`,
  height: `33px`,
  left: `0px`,
  top: `0px`,
});

const Vector2 = styled('img')({
  height: `33px`,
  width: `33px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group2 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `15.47px`,
  height: `24.74px`,
  left: `9px`,
  top: `4px`,
});

const Vector3 = styled('img')({
  height: `12.6px`,
  width: `7.73px`,
  position: `absolute`,
  left: `8px`,
  top: `0px`,
});

const Vector4 = styled('img')({
  height: `12.6px`,
  width: `7.73px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector5 = styled('img')({
  height: `10.7px`,
  width: `7.74px`,
  position: `absolute`,
  left: `8px`,
  top: `14px`,
});

const Vector6 = styled('img')({
  height: `10.7px`,
  width: `7.73px`,
  position: `absolute`,
  left: `0px`,
  top: `14px`,
});

const Vector7 = styled('img')({
  height: `7.94px`,
  width: `7.73px`,
  position: `absolute`,
  left: `8px`,
  top: `9px`,
});

const Vector8 = styled('img')({
  height: `7.94px`,
  width: `7.73px`,
  position: `absolute`,
  left: `0px`,
  top: `9px`,
});

const IconXrpCryptocurrenc = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `33px`,
  height: `33px`,
  left: `13px`,
  top: `555px`,
});

const Group3 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `33px`,
  height: `33px`,
  left: `0px`,
  top: `0px`,
});

const Vector9 = styled('img')({
  height: `33px`,
  width: `33px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector10 = styled('img')({
  height: `17.08px`,
  width: `20.63px`,
  position: `absolute`,
  left: `6px`,
  top: `8px`,
});

const IconUsdCoinCryptocur = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `33px`,
  height: `33px`,
  left: `12px`,
  top: `648px`,
});

const Group4 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `33px`,
  height: `33px`,
  left: `0px`,
  top: `0px`,
});

const Vector11 = styled('img')({
  height: `33px`,
  width: `33px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector12 = styled('img')({
  height: `24.23px`,
  width: `24.23px`,
  position: `absolute`,
  left: `4px`,
  top: `4px`,
});

const IconPolkadotCryptocu = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `33px`,
  height: `33px`,
  left: `12px`,
  top: `746px`,
});

const Group5 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `33px`,
  height: `33px`,
  left: `0px`,
  top: `0px`,
});

const Vector13 = styled('img')({
  height: `33px`,
  width: `33px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector14 = styled('img')({
  height: `18.29px`,
  width: `13.89px`,
  position: `absolute`,
  left: `10px`,
  top: `7px`,
});

const Ellipse3 = styled('img')({
  height: `113px`,
  width: `105px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `323px`,
  top: `120px`,
});

const BoutonSignIn = styled('img')({
  height: `73px`,
  width: `114px`,
  position: `absolute`,
  left: `32px`,
  top: `211px`,
});

const BoutonSignIn1 = styled('img')({
  height: `64px`,
  width: `75px`,
  position: `absolute`,
  left: `372px`,
  top: `336px`,
});

const BoutonSignIn2 = styled('img')({
  height: `368px`,
  width: `78px`,
  position: `absolute`,
  left: `372px`,
  top: `420px`,
});

const Drag = styled('img')({
  height: `37px`,
  width: `49px`,
  position: `absolute`,
  left: `396px`,
  top: `33px`,
});

const SignIn = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `700`,
  fontSize: `32px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `77px`,
  textTransform: `none`,
  width: `188px`,
  height: `67px`,
  position: `absolute`,
  left: `37px`,
  top: `7px`,
});

const Rectangle7 = styled('div')({
  opacity: `0.5`,
  backgroundColor: `rgba(147, 136, 136, 1)`,
  boxShadow: `0px 12px 21px rgba(68, 97, 242, 0.15)`,
  border: `3px solid rgba(147, 136, 136, 1)`,
  borderRadius: `10px`,
  mixBlendMode: `luminosity`,
  width: `233px`,
  height: `64px`,
  position: `absolute`,
  left: `241px`,
  top: `862px`,
});

const Rectangle71 = styled('div')({
  opacity: `0.5`,
  backgroundColor: `rgba(47, 43, 43, 0)`,
  boxShadow: `0px 12px 21px rgba(68, 97, 242, 0.15)`,
  border: `3px solid rgba(147, 136, 136, 1)`,
  borderRadius: `10px`,
  mixBlendMode: `luminosity`,
  width: `237px`,
  height: `64px`,
  position: `absolute`,
  left: `0px`,
  top: `862px`,
});

const Fiat = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `400`,
  fontSize: `25px`,
  letterSpacing: `2.25px`,
  textDecoration: `none`,
  lineHeight: `77px`,
  textTransform: `none`,
  width: `94px`,
  height: `64px`,
  position: `absolute`,
  left: `70px`,
  top: `861px`,
});

const Crypto = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Solway`,
  fontWeight: `700`,
  fontSize: `25px`,
  letterSpacing: `2.25px`,
  textDecoration: `none`,
  lineHeight: `77px`,
  textTransform: `none`,
  width: `111px`,
  height: `64px`,
  position: `absolute`,
  left: `313px`,
  top: `861px`,
});

function Component4(props) {
  return (
    <Component41 className={props.className}>
      {/* <ArrowUpRight1 /> */}
      {/* <ArrowDownRight1 /> */}
      <WalletPortfolio>
        <Background>
          <Ellipse2 src={Ellipse2Image} loading="lazy" alt={'Ellipse 2'} />
        </Background>
        <Group237458>
          <Group237456>
            <Forms>
              <ForgetPasswordText>
                <Q1015Bnb>{`10.15 BNB`}</Q1015Bnb>
                <Bnb226692>
                  <Bnb226692Span1>{`BNB
`}</Bnb226692Span1>
                  <Bnb226692Span2>{`$226.69 `}</Bnb226692Span2>
                  <Bnb226692Span3>{`+2%`}</Bnb226692Span3>
                </Bnb226692>
                <Mohit>{`Mohit`}</Mohit>
                <CryptoBalance12669>
                  <CryptoBalance12669Span1>{`Crypto Balance
`}</CryptoBalance12669Span1>
                  <CryptoBalance12669Span2>{`$126.69`}</CryptoBalance12669Span2>
                </CryptoBalance12669>
                <Eth1210043>
                  <Eth1210043Span1>{`ETH
`}</Eth1210043Span1>
                  <Eth1210043Span2>{`$121.00 `}</Eth1210043Span2>
                  <Eth1210043Span3>{`+4.3%`}</Eth1210043Span3>
                </Eth1210043>
                <Dot09096>
                  <Dot09096Span1>{`DOT
`}</Dot09096Span1>
                  <Dot09096Span2>{`$0.90 `}</Dot09096Span2>
                  <Dot09096Span3>{`-9.6%`}</Dot09096Span3>
                </Dot09096>
                <Usdc10043>
                  <Usdc10043Span1>{`USDC
`}</Usdc10043Span1>
                  <Usdc10043Span2>{`$1.00 `}</Usdc10043Span2>
                  <Usdc10043Span3>{`+4.3%`}</Usdc10043Span3>
                </Usdc10043>
                <Xrp11013>
                  <Xrp11013Span1>{`XRP
`}</Xrp11013Span1>
                  <Xrp11013Span2>{`$1.10 `}</Xrp11013Span2>
                  <Xrp11013Span3>{`-1.3%`}</Xrp11013Span3>
                </Xrp11013>
                <Q125Dot>{`12.5 DOT`}</Q125Dot>
                <Q2226Eth>{`22.26 ETH`}</Q2226Eth>
                <Q10026Xrp>{`100.26 XRP`}</Q10026Xrp>
                <Q10026Usdc>{`100.26 USDC`}</Q10026Usdc>
              </ForgetPasswordText>
              <Line>
                <Line1></Line1>
              </Line>
            </Forms>
          </Group237456>
        </Group237458>
        <Line4 src={Line4Image} loading="lazy" alt={'Line 4'} />
        <IconBinanceCoinCrypt>
          <Group>
            <Vector src={VectorImage} loading="lazy" alt={'Vector'} />
            <Vector1 src={Vector1Image} loading="lazy" alt={'Vector'} />
          </Group>
        </IconBinanceCoinCrypt>
        <IconEthereumCryptocu>
          <Group1>
            <Vector2 src={Vector2Image} loading="lazy" alt={'Vector'} />
            <Group2>
              <Vector3 src={Vector3Image} loading="lazy" alt={'Vector'} />
              <Vector4 src={Vector4Image} loading="lazy" alt={'Vector'} />
              <Vector5 src={Vector5Image} loading="lazy" alt={'Vector'} />
              <Vector6 src={Vector6Image} loading="lazy" alt={'Vector'} />
              <Vector7 src={Vector7Image} loading="lazy" alt={'Vector'} />
              <Vector8 src={Vector8Image} loading="lazy" alt={'Vector'} />
            </Group2>
          </Group1>
        </IconEthereumCryptocu>
        <IconXrpCryptocurrenc>
          <Group3>
            <Vector9 src={Vector9Image} loading="lazy" alt={'Vector'} />
            <Vector10 src={Vector10Image} loading="lazy" alt={'Vector'} />
          </Group3>
        </IconXrpCryptocurrenc>
        <IconUsdCoinCryptocur>
          <Group4>
            <Vector11 src={Vector11Image} loading="lazy" alt={'Vector'} />
            <Vector12 src={Vector12Image} loading="lazy" alt={'Vector'} />
          </Group4>
        </IconUsdCoinCryptocur>
        <IconPolkadotCryptocu>
          <Group5>
            <Vector13 src={Vector13Image} loading="lazy" alt={'Vector'} />
            <Vector14 src={Vector14Image} loading="lazy" alt={'Vector'} />
          </Group5>
        </IconPolkadotCryptocu>
        <Ellipse3 src={Ellipse3Image} loading="lazy" alt={'Ellipse 3'} />
        <BoutonSignIn
          src={BoutonSignInImage}
          loading="lazy"
          alt={'Bouton Sign In'}
        />
        <BoutonSignIn1
          src={BoutonSignIn1Image}
          loading="lazy"
          alt={'Bouton Sign In'}
        />
        <BoutonSignIn2
          src={BoutonSignIn2Image}
          loading="lazy"
          alt={'Bouton Sign In'}
        />
        <Drag src={DragImage} loading="lazy" alt={'drag'} />
        <SignIn>{`UpiCrypto`}</SignIn>
        <Rectangle7></Rectangle7>
        <Rectangle71></Rectangle71>
        <Fiat>{`Fiat`}</Fiat>
        <Crypto>{`Crypto`}</Crypto>
      </WalletPortfolio>
    </Component41>
  );
}

export default Component4;
