import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import { Web3Auth } from "@web3auth/modal";
import { Card, Row } from "web3uikit";
import Header from "@/components/HEader";
import Crypto from "@/components/Crypto";
import Fiat from "@/components/Fiat";
import Login from "./login";
import { useSession, signIn, signOut } from "next-auth/react";
import { useRouter } from "next/navigation";
import { Col, Nav, Tab } from "react-bootstrap";
//

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { push } = useRouter();
  const { data: session } = useSession();
  useEffect(() => {
    if (!session) {
      push("/login");
    }
  }, []);
  const [activeKey, setaActiveKey] = useState("fiat");
  console.log("acftive", activeKey);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={styles.main}
        style={{ background: "#1C1717", height: "100%" }}
      >
        {session && (
          <>
            <Header />

            <Tab.Container
              id="left-tabs-example"
              onSelect={(key) => {
                setaActiveKey(key);
              }}
              defaultActiveKey="fiat"
              // key={activeKey}
            >
              <Row>
                <Col md={3}></Col>
                <Col md={6}>
                  <div className="w-100">
                    <Tab.Content>
                      <Tab.Pane eventKey="fiat">
                        <Fiat />
                      </Tab.Pane>
                      <Tab.Pane eventKey="crypto">
                        <Crypto />
                      </Tab.Pane>
                    </Tab.Content>
                  </div>
                </Col>
                <Col md={3}></Col>
              </Row>
              <Row>
                <Col md={3}></Col>
                <Col md={6}>
                  <div className="w-100 d-flex justify-content-center">
                    <Nav className="d-flex flex-grow-1">
                      <Nav.Item
                        className="flex-grow-1 mx-2 content-tab"
                        style={{
                          background: `${
                            activeKey == "fiat" ? "gray" : "#000000"
                          }`,
                          color: "#fff",
                          border: "1px solid #fff",
                        }}
                      >
                        <Nav.Link eventKey="fiat" className="flex-grow-1">
                          Fiat
                        </Nav.Link>
                      </Nav.Item>
                      <Nav.Item
                        className="flex-grow-1 mx-2 content-tab"
                        style={{
                          background: `${
                            activeKey == "crypto" ? "gray" : "#000000"
                          }`,
                          color: "#fff !important",
                          border: "1px solid #fff",
                        }}
                      >
                        <Nav.Link eventKey="crypto" className="flex-grow-1">
                          Crypto
                        </Nav.Link>
                      </Nav.Item>
                    </Nav>
                  </div>
                </Col>

                <Col md={3}></Col>
              </Row>
            </Tab.Container>
          </>
        )}
      </main>
    </>
  );
}
